language: cpp

os:
    - linux

dist: xenial

cache: ccache

addons:
    snaps:
        - cppcheck

before_install:
    - sudo apt-get update
    - sudo apt-get install -y g++ cmake build-essential autoconf libtool pkg-config ccache
    - ./travis/installGrpc.sh

script:
    - ./build.sh
    - cppcheck --enable=all --inconclusive --std=c++11 -DGOOGLE_PROTOBUF_VERSION=3006001 --project=compile_commands.json -i third_party -j `nproc --all` -q
